#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("GoogleMusic.Resource", IsApplication=true)]

namespace GoogleMusic
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
			Xamarin.Tables.Resource.Animation.slide_in_left = GoogleMusic.Resource.Animation.slide_in_left;
			Xamarin.Tables.Resource.Animation.slide_in_right = GoogleMusic.Resource.Animation.slide_in_right;
			Xamarin.Tables.Resource.Animation.slide_out_left = GoogleMusic.Resource.Animation.slide_out_left;
			Xamarin.Tables.Resource.Animation.slide_out_right = GoogleMusic.Resource.Animation.slide_out_right;
			Xamarin.Tables.Resource.Drawable.dialog_disclosure = GoogleMusic.Resource.Drawable.dialog_disclosure;
			Xamarin.Tables.Resource.Drawable.dialog_expander_ic_minimized = GoogleMusic.Resource.Drawable.dialog_expander_ic_minimized;
			Xamarin.Tables.Resource.Id.LeftBtn = GoogleMusic.Resource.Id.LeftBtn;
			Xamarin.Tables.Resource.Id.LeftButtonLayout = GoogleMusic.Resource.Id.LeftButtonLayout;
			Xamarin.Tables.Resource.Id.LinearLayout01 = GoogleMusic.Resource.Id.LinearLayout01;
			Xamarin.Tables.Resource.Id.RightBtn = GoogleMusic.Resource.Id.RightBtn;
			Xamarin.Tables.Resource.Id.RightButtonLayout = GoogleMusic.Resource.Id.RightButtonLayout;
			Xamarin.Tables.Resource.Id.dialog_BoolField = GoogleMusic.Resource.Id.dialog_BoolField;
			Xamarin.Tables.Resource.Id.dialog_Button = GoogleMusic.Resource.Id.dialog_Button;
			Xamarin.Tables.Resource.Id.dialog_DisclosureField = GoogleMusic.Resource.Id.dialog_DisclosureField;
			Xamarin.Tables.Resource.Id.dialog_ImageLeft = GoogleMusic.Resource.Id.dialog_ImageLeft;
			Xamarin.Tables.Resource.Id.dialog_ImageRight = GoogleMusic.Resource.Id.dialog_ImageRight;
			Xamarin.Tables.Resource.Id.dialog_LabelField = GoogleMusic.Resource.Id.dialog_LabelField;
			Xamarin.Tables.Resource.Id.dialog_LabelSubtextField = GoogleMusic.Resource.Id.dialog_LabelSubtextField;
			Xamarin.Tables.Resource.Id.dialog_Panel = GoogleMusic.Resource.Id.dialog_Panel;
			Xamarin.Tables.Resource.Id.dialog_RadioButtonList = GoogleMusic.Resource.Id.dialog_RadioButtonList;
			Xamarin.Tables.Resource.Id.dialog_SliderField = GoogleMusic.Resource.Id.dialog_SliderField;
			Xamarin.Tables.Resource.Id.dialog_Spinner = GoogleMusic.Resource.Id.dialog_Spinner;
			Xamarin.Tables.Resource.Id.dialog_ValueField = GoogleMusic.Resource.Id.dialog_ValueField;
			Xamarin.Tables.Resource.Id.iFormFieldValue = GoogleMusic.Resource.Id.iFormFieldValue;
			Xamarin.Tables.Resource.Id.navContent = GoogleMusic.Resource.Id.navContent;
			Xamarin.Tables.Resource.Id.title = GoogleMusic.Resource.Id.title;
			Xamarin.Tables.Resource.Layout.dialog_achievements = GoogleMusic.Resource.Layout.dialog_achievements;
			Xamarin.Tables.Resource.Layout.dialog_boolfieldleft = GoogleMusic.Resource.Layout.dialog_boolfieldleft;
			Xamarin.Tables.Resource.Layout.dialog_boolfieldright = GoogleMusic.Resource.Layout.dialog_boolfieldright;
			Xamarin.Tables.Resource.Layout.dialog_boolfieldsubleft = GoogleMusic.Resource.Layout.dialog_boolfieldsubleft;
			Xamarin.Tables.Resource.Layout.dialog_boolfieldsubright = GoogleMusic.Resource.Layout.dialog_boolfieldsubright;
			Xamarin.Tables.Resource.Layout.dialog_button = GoogleMusic.Resource.Layout.dialog_button;
			Xamarin.Tables.Resource.Layout.dialog_datefield = GoogleMusic.Resource.Layout.dialog_datefield;
			Xamarin.Tables.Resource.Layout.dialog_fieldsetlabel = GoogleMusic.Resource.Layout.dialog_fieldsetlabel;
			Xamarin.Tables.Resource.Layout.dialog_floatimage = GoogleMusic.Resource.Layout.dialog_floatimage;
			Xamarin.Tables.Resource.Layout.dialog_labelfieldbelow = GoogleMusic.Resource.Layout.dialog_labelfieldbelow;
			Xamarin.Tables.Resource.Layout.dialog_labelfieldright = GoogleMusic.Resource.Layout.dialog_labelfieldright;
			Xamarin.Tables.Resource.Layout.dialog_onofffieldright = GoogleMusic.Resource.Layout.dialog_onofffieldright;
			Xamarin.Tables.Resource.Layout.dialog_panel = GoogleMusic.Resource.Layout.dialog_panel;
			Xamarin.Tables.Resource.Layout.dialog_root = GoogleMusic.Resource.Layout.dialog_root;
			Xamarin.Tables.Resource.Layout.dialog_selectlist = GoogleMusic.Resource.Layout.dialog_selectlist;
			Xamarin.Tables.Resource.Layout.dialog_selectlistfield = GoogleMusic.Resource.Layout.dialog_selectlistfield;
			Xamarin.Tables.Resource.Layout.dialog_textarea = GoogleMusic.Resource.Layout.dialog_textarea;
			Xamarin.Tables.Resource.Layout.dialog_textfieldbelow = GoogleMusic.Resource.Layout.dialog_textfieldbelow;
			Xamarin.Tables.Resource.Layout.dialog_textfieldright = GoogleMusic.Resource.Layout.dialog_textfieldright;
			Xamarin.Tables.Resource.Layout.NavListView = GoogleMusic.Resource.Layout.NavListView;
			Xamarin.Tables.Resource.String.library_name = GoogleMusic.Resource.String.library_name;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_right = 2130968579;
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000a
			public const int behindFadeDegree = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int behindFadeEnabled = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public const int selectorDrawable = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int selectorEnabled = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int shadowDrawable = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int shadowWidth = 2130771976;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060005
			public const int black = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int blue = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int green = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int holo_blue_bright = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int red = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int white = 2131099652;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070005
			public const int list_padding = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int menu_header_line = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int menu_header_padding_top = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int menu_icon_side = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int menu_item_padding = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int shadow_width = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int slidingmenu_offset = 2131165188;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blackbutton = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int default_album = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int default_album_large = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int defaultshadow = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int defaultshadowright = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dialog_disclosure = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int dialog_expander_ic_minimized = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int forward = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_launcher = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int indicator = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int menubar = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int menuButton = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int new_indicator = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int shadow = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int shadowright = 2130837520;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05001e
			public const int LeftBtn = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int LeftButtonLayout = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int LinearLayout01 = 2131034140;
			
			// aapt resource value: 0x7f050021
			public const int RightBtn = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int RightButtonLayout = 2131034144;
			
			// aapt resource value: 0x7f050005
			public const int albumArt = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int albumName = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int artistName = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int button1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int content_frame = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int dialog_BoolField = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int dialog_Button = 2131034127;
			
			// aapt resource value: 0x7f050015
			public const int dialog_DisclosureField = 2131034133;
			
			// aapt resource value: 0x7f050011
			public const int dialog_ImageLeft = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int dialog_ImageRight = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int dialog_LabelField = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int dialog_LabelSubtextField = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int dialog_Panel = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int dialog_RadioButtonList = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int dialog_SliderField = 2131034130;
			
			// aapt resource value: 0x7f050017
			public const int dialog_Spinner = 2131034135;
			
			// aapt resource value: 0x7f050010
			public const int dialog_ValueField = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int fullscreen = 2131034115;
			
			// aapt resource value: 0x7f050018
			public const int iFormFieldValue = 2131034136;
			
			// aapt resource value: 0x7f050028
			public const int imageView1 = 2131034152;
			
			// aapt resource value: 0x7f050000
			public const int left = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout1 = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int linearLayout2 = 2131034121;
			
			// aapt resource value: 0x7f050024
			public const int linearLayout3 = 2131034148;
			
			// aapt resource value: 0x7f050019
			public const int listView = 2131034137;
			
			// aapt resource value: 0x7f050002
			public const int margin = 2131034114;
			
			// aapt resource value: 0x7f05001b
			public const int menu_frame = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int myButton = 2131034138;
			
			// aapt resource value: 0x7f050022
			public const int navContent = 2131034146;
			
			// aapt resource value: 0x7f050001
			public const int right = 2131034113;
			
			// aapt resource value: 0x7f050029
			public const int row_icon = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int row_title = 2131034154;
			
			// aapt resource value: 0x7f050026
			public const int seekBar1 = 2131034150;
			
			// aapt resource value: 0x7f050004
			public const int selected_view = 2131034116;
			
			// aapt resource value: 0x7f05002c
			public const int slidingmenulayout = 2131034156;
			
			// aapt resource value: 0x7f05002b
			public const int slidingmenumain = 2131034155;
			
			// aapt resource value: 0x7f05002d
			public const int slidingmenurowicon = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int slidingmenurowtitle = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int songTitle = 2131034159;
			
			// aapt resource value: 0x7f050025
			public const int textView1 = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int textView2 = 2131034151;
			
			// aapt resource value: 0x7f050023
			public const int textView3 = 2131034147;
			
			// aapt resource value: 0x7f05001f
			public const int title = 2131034143;
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int num_cols = 2131296256;
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int albumCell = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int albumHeaderCell = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int artistCell = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int content_frame = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_achievements = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_boolfieldleft = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_boolfieldright = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dialog_boolfieldsubleft = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int dialog_boolfieldsubright = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int dialog_button = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_datefield = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_fieldsetlabel = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_floatimage = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int dialog_labelfieldbelow = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int dialog_labelfieldright = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int dialog_onofffieldright = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int dialog_panel = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int dialog_root = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int dialog_selectlist = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int dialog_selectlistfield = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int dialog_textarea = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int dialog_textfieldbelow = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int dialog_textfieldright = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int list = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Main = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int menu = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int menu_frame = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int NavListView = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int nowplaying = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int row = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int shadow = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int slidingmenumain = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int slidingmenumainlist = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int slidingmenurow = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int songCell = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int window_title = 2130903075;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080017
			public const int about = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int about_msg = 2131230746;
			
			// aapt resource value: 0x7f08000c
			public const int anim_fold = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int anim_scale = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int anim_slide = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int anim_zoom = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int animations = 2131230729;
			
			// aapt resource value: 0x7f08001b
			public const int apache_license = 2131230747;
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int attach = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int changing_fragments = 2131230734;
			
			// aapt resource value: 0x7f080019
			public const int contact = 2131230745;
			
			// aapt resource value: 0x7f080003
			public const int general = 2131230723;
			
			// aapt resource value: 0x7f080013
			public const int github = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int github_label = 2131230740;
			
			// aapt resource value: 0x7f080010
			public const int left = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int left_and_right = 2131230738;
			
			// aapt resource value: 0x7f080000
			public const int library_name = 2131230720;
			
			// aapt resource value: 0x7f080018
			public const int licenses = 2131230744;
			
			// aapt resource value: 0x7f08001c
			public const int no_email = 2131230748;
			
			// aapt resource value: 0x7f080002
			public const int properties = 2131230722;
			
			// aapt resource value: 0x7f080016
			public const int responsive_explanation = 2131230742;
			
			// aapt resource value: 0x7f08000f
			public const int responsive_ui = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int right = 2131230737;
			
			// aapt resource value: 0x7f080006
			public const int title_bar = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int title_bar_content = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int title_bar_slide = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int viewpager = 2131230724;
			
			// aapt resource value: 0x7f080015
			public const int what_is_this = 2131230741;
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingMenu = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 10
			public const int SlidingMenu_behindFadeDegree = 10;
			
			// aapt resource value: 9
			public const int SlidingMenu_behindFadeEnabled = 9;
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorDrawable = 12;
			
			// aapt resource value: 11
			public const int SlidingMenu_selectorEnabled = 11;
			
			// aapt resource value: 7
			public const int SlidingMenu_shadowDrawable = 7;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowWidth = 8;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
